name: znz

services:
  db:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_DB: znz
      POSTGRES_USER: znz
      POSTGRES_PASSWORD: znz
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  db-data:
    driver: local