name: znz-client

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Automatically uses Node.js version specified in package.json engines field
          node-version-file: './client/package.json'
          cache: 'npm'

      # Step 3: Configure Cache
      # - name: Cache NPM Dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.npm
      #       ./sfu/node_modules
      #       ./client/node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      # Step 4: Install dependencies for SFU project
      # - name: Install Dependencies (SFU)
      #   working-directory: ./sfu
      #   run: |
      #     npm install

      # Step 5: Install dependencies for Client project
      # - name: Install Dependencies (Client)
      #   working-directory: ./client
      #   run: |
      #     npm ci || npm install

      - name: Install Dependencies
        run: |
          npm install

      # Step 6: Run Lint for SFU project
      - name: Lint SFU Project
        run: npm run lint

      # Step 8: Test SFU project (Optional)
      # Uncomment this if testing is enabled for the SFU project
      # - name: Test SFU Project
      #   working-directory: ./sfu
      #   run: npm test

      # Step 9: Test Client project (Optional)
      # Uncomment this if testing is enabled for the Client project
      # - name: Test Client Project
      #   working-directory: ./client
      #   run: npm test
