name: znz-client

on: [pull_request, workflow_dispatch]

concurrency:
  # Cancel a currently running workflow from the same PR, branch or tag when a
  # new workflow is triggered.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      matrix:
        ci:
        - os: ubuntu-20.04
          node: 18
        - os: ubuntu-22.04
          node: 20
        - os: ubuntu-24.04
          node: 22
        - os: macos-13
          node: 18
        - os: macos-14
          node: 20
        - os: macos-15
          node: 22
        - os: windows-2022
          node: 22

    runs-on: ${{ matrix.ci.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.ci.node }}

      - name: Configure cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ./sfu/node_modules
            ./client/node_modules
          key: ${{ matrix.ci.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ matrix.ci.os }}-node-

      # Install dependencies for sfu project
      - name: npm ci (sfu)
        working-directory: ./sfu
        run: npm ci --force --foreground-scripts

      # Install dependencies for client project
      - name: npm ci (client)
        working-directory: ./client
        run: npm ci --force --foreground-scripts

      # Lint and test sfu project
      - name: npm run lint (sfu)
        working-directory: ./sfu
        run: npm run lint

      # - name: npm run test (sfu)
      #   working-directory: ./sfu
      #   run: npm run test

      # Lint and test client project
      - name: npm run lint (client)
        working-directory: ./client
        run: npm run lint

      # - name: npm run test (client)
      #   working-directory: ./client
      #   run: npm run test
