name: znz-client

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './package.json'
          cache: 'npm'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          rm -rf node_modules package-lock.json yarn.lock
          npm ci

      # Step 4: Fix Formatting Issues
      - name: Prettier Auto Fix
        run: |
          npm run lint:fix

      # Step 5: Run Linting
      - name: Run Lint
        run: |
          npm run lint

      # Step 6: Build SFU and Client Projects
      - name: Build Projects
        run: |
          npm run build

      # Step 7: Verify Build Artifacts
      - name: Verify SFU Build Output
        working-directory: ./sfu
        run: |
          ls -la dist

      - name: Verify Client Build Output
        working-directory: ./client
        run: |
          ls -la build
